language: node_js
node_js:
  - "node"
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - python
      - cmake
      - build-essential
      - gcc-5
      - g++-5
before_install: 
  - npm install -g node-gyp
script:
  - npm run test
branches:
  only:
    - master
cache:
  directories:
  - node_modules