language: node_js
node_js:
  - "node"
addons:
  apt:
    packages:
      - python3.6
      - build-essential
      - gcc-4.8
      - g++-4.8  
before_install: 
  - npm install -g node-gyp
script:
  - npm run test
branches:
  only:
    - master
cache:
  directories:
  - node_modules