language: node_js
node_js:
  - "node"
addons:
  apt:
    packages:
      - python
      - cmake
      - build-essential
      - gcc-5.1 
      - g++-5.1
before_install: 
  - npm install -g node-gyp
script:
  - npm run test
branches:
  only:
    - master
cache:
  directories:
  - node_modules