sudo: false
env:
  - CXX=g++-4.8
language: node_js
node_js:
  - "4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm run test
  - npm run example:ci
branches:
  only:
    - master
cache:
  directories:
  - node_modules
deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: example/webapp/build
 on:
   branch: master